[colors.primary]
background = '#0a1519'
foreground = '#d9e4eb'

[colors.selection]
text = '#d9e4eb'
background = '#004d63'

[colors.cursor]
text = '#0a1519'
cursor = '#61d4ff'

[colors.normal]
black   = '#0a1519'
red     = '#ff518a'
green   = '#61ff72'
yellow  = '#fff451'
blue    = '#3ec1f2'
magenta = '#005576'
cyan    = '#61d4ff'
white   = '#ecf9ff'

[colors.bright]
black   = '#96a1a5'
red     = '#ff88af'
green   = '#90ff9c'
yellow  = '#fff890'
blue    = '#78daff'
magenta = '#90e0ff'
cyan    = '#b7ebff'
white   = '#f7fcff'
