[colors.primary]
background = '#14121c'
foreground = '#e7e0ef'

[colors.selection]
text = '#e7e0ef'
background = '#5100cf'

[colors.cursor]
text = '#14121c'
cursor = '#cebdff'

[colors.normal]
black   = '#14121c'
red     = '#ff7290'
green   = '#7fff99'
yellow  = '#ffda72'
blue    = '#baa7f2'
magenta = '#4c3e76'
cyan    = '#cebdff'
white   = '#f3efff'

[colors.bright]
black   = '#9c99a5'
red     = '#ff9fb3'
green   = '#a5ffb8'
yellow  = '#ffe7a5'
blue    = '#d5c6ff'
magenta = '#dcd0ff'
cyan    = '#e8e1ff'
white   = '#faf8ff'
