[colors.primary]
background = '#0b141b'
foreground = '#dae4ed'

[colors.selection]
text = '#dae4ed'
background = '#004c6c'

[colors.cursor]
text = '#0b141b'
cursor = '#85cfff'

[colors.normal]
black   = '#0b141b'
red     = '#ff729e'
green   = '#7fff8e'
yellow  = '#fff672'
blue    = '#67bbf2'
magenta = '#0e4d76'
cyan    = '#85cfff'
white   = '#eff8ff'

[colors.bright]
black   = '#99a0a5'
red     = '#ff9fbd'
green   = '#a5ffb0'
yellow  = '#fff9a5'
blue    = '#97d6ff'
magenta = '#a9ddff'
cyan    = '#c8e9ff'
white   = '#f8fcff'
